### ISSUE TITLE
Skirmish Screen Freeze

### ISSUE THREAD

**Issue by m-flak** [markol/machines#4]
I've run into quite a challenging problem. The game freezes on the skirmish screen. 
At the time of this posting, I am unsure of where to look.

I added a ton of cerr's and even assert's in **_libdev/machgui/ctxskirm.cpp_**, trying to trace the issue. The last message I saw was the final iteration of `MachGuiCtxSkirmish::updateMapSizeList`.

The **crash.log** shows me a repetitive stacktrace of calls to `boundary()` / `absoluteBoundary()` in **_libdev/gui/displaya.cpp_**.
My next strategy will be to utilize a debugger. :)

Any insights, @markol? You are more familiar with this codebase than I.

**Comment by awpe** [comment]
Check menu building routines, some of the selection menus(terrains or map types) are iterating too much (trying to access nonexisting items)

**Comment by awpe** [comment]
I would have made my repo public as I have done a lot of work on this code base including some comments removing, however for the sake of simplicity I've added sounds and models there as well so I don't know whether it is legal to open such repo for public access....

**Comment by awpe** [comment]
You can pass me your deploy key however...

**Comment by m-flak** [comment]
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3H1JMDqHtOrXD6D19SfYckOVj/2rSYiz2Di+zTUts/GWygq09l2S0hQKL/GcB3uiwRrwyelwrAHIMLfpfuLel8EGWUI93oQ0LFvdME1LTnRQrC/Z67qCKwI+8S/zQS+xSH//Rr0jNUMQVCit+EBdEvbOGVn69VCwrx2v0C1VKDv1786zx5zTBeTe/+zqgGMysZ2eQy+UX3D8yIAlzj6NSs3LHwpZ3pAgpbPcK5pFGXh6QiXqpLu2oLocOyI/f1d2RNPPxijGxtFEQvzoADHc5HpJ5dJznUQnS8zAlf8jqqocKK7iREIH77FMbqHzMpRgtj8er1mVVpzWIUemA5heKLfSHh9cghFStr8MwjdiIeiOQJSo8fO7i+T3uoD5AoLuLYk/1gwiMfQP01aHbUyiXl7G8o4liyAtWK+KaT/7JswuoRVewXclXQjIrIqzV0R9zpGIkwS2OiiUx+5L6xUqYC1pSSoCvR7Vkkx2wUxOpPgJxTnmhbDdGhTppORyDZHk= matt91.mek@gmail.com
```

**Comment by awpe** [comment]
Added https://github.com/awpe/machines/tree/development

**Comment by m-flak** [comment]
`MachGuiDatabase::CUSTOM` :gun: 
I figured it out! Thanks for the hint!

**Comment by awpe** [comment]
You are welcome, were you able to build my version? It fixes some bugs, enables anti-aliasing and enables high FPS (no limit) which helps AI a lot.

**Comment by m-flak** [comment]
I have not. I have only glanced at our tree differences using Meld (awesome
tool).

Are you refactoring the codebase? I saw many renamed files. I am curious to
what's going on.

I want to go straight into modding, so I'm going to start looking at
gameplay.

I think I will keep working off my fork, but I might want to use your fork
as a base. We shall see! 😁

**Comment by awpe** [comment]
I wanted to made game playable in debug mode and to tweak AI and overall gaming experience however after a month or so going deep into code I've finally realized that it would take less time with better results to just take UT4 engine and made it there from scratch. Original code is awful by all means, it will always fail in debug mode at some timepoints there are some assertion that fail and they have comments like "TODO: check why this always fails", in release mode this code suppresses all assertions so game becomes playable however in case of problems it will crash and the problems are not obvious as a lot of messy stuff is going on around.

Dataflow and control flow are very much hidden from each other so in any particular point you can not tell what is data state and where you are from the logic point of view.

I know this was created in pre-GIT era on 800*600 monitors with attempt for it to run on DOS/PS1/MACOS, and only made its way to be released for windows platform with directX so I'm not complaining for it, just stating it might be timewasting to further solve problems that do not exist nowadays.

**Comment by awpe** [comment]
If you want to "fix" it you better start from taking paper spreadsheet with a pen and dig into how path finding works as 99.9999% crashes are related to path finding ending up with incorrect and/or impossible coordinates due to IEEE754-stuff if you know what I mean :-D

**Comment by m-flak** [comment]
Was there a reason for disabling the "CD audio"? I noticed that most of the OpenAL/Alure stuff was commented out? Were you experiencing issues with it?
